#ifndef config_H_
#define config_H_

#include "constant.h"


#define NB_RELAYS_MAX           32

// WS_MODE_SERIAL = WS_MODE_SERIAL_USB | WS_MODE_SERIAL_ETHERNET | WS_MODE_SERIAL_LED | WS_MODE_SERIAL_ALL
#define WS_MODE_SERIAL             WS_MODE_SERIAL_ALL

// WS_MODE_VERBOSE = WS_MODE_VERBOSE_NONE | WS_MODE_VERBOSE_HELP | WS_MODE_VERBOSE_LIST | WS_MODE_VERBOSE_WEBAPP | WS_MODE_VERBOSE_ALL
#define WS_MODE_VERBOSE            WS_MODE_VERBOSE_ALL

// PIN_WS_RELAY_WIRING = PIN_WS_RELAY_WIRING_NC | PIN_WS_RELAY_WIRING_NO
#define WS_RELAY_WIRING            WS_RELAY_WIRING_NC

// WS_TYPE_MAC = WS_TYPE_MAC_STATIC | WS_TYPE_MAC_DYNAMIC
#define WS_TYPE_MAC                WS_TYPE_MAC_STATIC

// WS_MODE_BONJOUR = WS_MODE_BONJOUR_NONE | WS_MODE_BONJOUR_STATIC | WS_MODE_BONJOUR_DYNAMIC
#define WS_MODE_BONJOUR            WS_MODE_BONJOUR_STATIC

// WS_DATA_STORAGE = WS_ACL_ALLOW_NONE | WS_ACL_ALLOW_RESET
#define WS_ACL_ALLOW               WS_ACL_ALLOW_RESET

// WS_DATA_STORAGE = WS_DATA_STORAGE_NONE | WS_DATA_STORAGE_EEPROM
#define WS_DATA_STORAGE            WS_DATA_STORAGE_EEPROM

// WS_LOG_LEVEL = WS_LOG_LEVEL_OFF | WS_LOG_LEVEL_FATAL | WS_LOG_LEVEL_ERROR | WS_LOG_LEVEL_WARN | WS_LOG_LEVEL_INFO | WS_LOG_LEVEL_DEBUG | WS_LOG_LEVEL_TRACE | WS_LOG_LEVEL_ALL
#define WS_LOG_LEVEL               WS_LOG_LEVEL_OFF



// board metadata
// =====================
// a number between 2 and 253
#define DEVICE_NUMBER   12
#define DEVICE_NAME     "webrelay"
#define LOOP_SLEEP_MS   250
// =====================


// USB conf
// =====================
#define USB_SPEED       9600
// =====================


// ETH conf
// =====================
#define DHCP_TIMEOUT_MS 30000
#define WEB_PORT        80
// =====================


#endif // config_H_
