swagger: "2.0"
info:
  description: "
  Webcontroller Relay (Arduino) \n
  https://github.com/1e1/arduino-webcontroller-relay
  "
  version: "1.0.0"
  title: "WebController-Relay"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "2.71828183E0+github@gmail.com"
host: "webrelay.local"
basePath: "/"
schemes:
- "http"
paths:
  /r/{relay_id}:
    get:
      description: "read state"
      produces:
      - "text/plain"
      parameters:
      - in: "path"
        name: "relay_id"
        type: "integer"
        maximum: 127
        minimum: 0
        description: "relay id"
        required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Relay"
  /w/{relay_id}/{state}:
    get:
      description: "write state"
      produces:
      - "text/plain"
      parameters:
      - in: "path"
        name: "relay_id"
        type: "integer"
        maximum: 127
        minimum: 0
        description: "relay id"
        required: true
      - in: "path"
        name: "state"
        type: "integer"
        maximum: 1
        minimum: 0
        description: "targeted state"
        required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Relay"
definitions:
  Relay:
    type: "string"
    pattern: '^[01] \d{1,3} N[OC] \d{1,3}$'
    description: "{state} {relay_id} {NC or NO} {pin_id}"