#ifndef CERTIFICATE_GENERATED_H_
#define CERTIFICATE_GENERATED_H_

namespace certificate {
    typedef enum { CT_ECC=0, CT_RSA=1 } CertType;

    const CertType serverCertType = CT_ECC;

    constexpr const char dname[] = "webrelay";

    const char serverKey[] PROGMEM = R"EOT(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIH6reSMNb6LxeMgAydAvPxUiTu6pc2kfCm8PmlDmdZm/oAoGCCqGSM49
AwEHoUQDQgAEKtZNZ+IXV1n8zMGwyo6FvhP2HDVT6foIUqviIdc8lTVnuu7I2kuT
2fHld4u5LeljVBfyu1XBdmScdRiDIcYaJg==
-----END EC PRIVATE KEY-----
)EOT";

    const char serverCert[] PROGMEM = R"EOT(
-----BEGIN CERTIFICATE-----
MIICIzCCAckCFFv/2chHgo7pHOve8xNvAoAp8BJeMAoGCCqGSM49BAMCMIGTMQsw
CQYDVQQGEwJGUjEMMAoGA1UECAwDQlpIMRAwDgYDVQQHDAdSb3Njb2ZmMQwwCgYD
VQQKDAMxZTExDTALBgNVBAsMBEBsYW4xFzAVBgNVBAMMDndlYnJlbGF5LmxvY2Fs
MS4wLAYJKoZIhvcNAQkBFh8yLjcxODI4MTgzRTArd2VicmVsYXlAZ21haWwuY29t
MB4XDTIzMDgwNDE4MjIxNVoXDTQ4MDcyODE4MjIxNVowgZMxCzAJBgNVBAYTAkZS
MQwwCgYDVQQIDANCWkgxEDAOBgNVBAcMB1Jvc2NvZmYxDDAKBgNVBAoMAzFlMTEN
MAsGA1UECwwEQGxhbjEXMBUGA1UEAwwOd2VicmVsYXkubG9jYWwxLjAsBgkqhkiG
9w0BCQEWHzIuNzE4MjgxODNFMCt3ZWJyZWxheUBnbWFpbC5jb20wWTATBgcqhkjO
PQIBBggqhkjOPQMBBwNCAAQq1k1n4hdXWfzMwbDKjoW+E/YcNVPp+ghSq+Ih1zyV
NWe67sjaS5PZ8eV3i7kt6WNUF/K7VcF2ZJx1GIMhxhomMAoGCCqGSM49BAMCA0gA
MEUCIBklF9/H/LzOs92WkIYOLKXadQ53l8rLlaUaBHwVIJoWAiEA9IRXx7iQ8eE5
PK5TTsYRge5+hP1Y6LFYUQZ2br6SNCU=
-----END CERTIFICATE-----
)EOT";
}

#endif // CERTIFICATE_GENERATED_H_
