#ifndef CERTIFICATE_GENERATED_H_
#define CERTIFICATE_GENERATED_H_

namespace certificate {
    typedef enum { CT_ECC=0, CT_RSA=1 } CertType;

    constexpr CertType serverCertType = CT_ECC;

    constexpr char dname[] = "esp8266";

    constexpr char serverKey[] PROGMEM = R"EOT(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGT//ug1T++zKCXaerT6sf2Sl0vdaOtCROfyxKARjoTQoAoGCCqGSM49
AwEHoUQDQgAEm72/P2sPpmdC4SKLOEynoLwBN8/eoqUfNrZnVMT3cOLAg83hKing
25eVLTbkGTQ+/d5lMdT8hBKWvPd0yNt27w==
-----END EC PRIVATE KEY-----
)EOT";

    constexpr char serverCert[] PROGMEM = R"EOT(
-----BEGIN CERTIFICATE-----
MIICKDCCAc+gAwIBAgIUJkJjLwEw/R+pTOmsLLyNEILvWaMwCgYIKoZIzj0EAwIw
gYExCzAJBgNVBAYTAkZSMQwwCgYDVQQIDANCWkgxEDAOBgNVBAcMB1Jvc2NvZmYx
DDAKBgNVBAoMAzFlMTENMAsGA1UECwwEQGxhbjEWMBQGA1UEAwwNZXNwODI2Ni5s
b2NhbDEdMBsGCSqGSIb3DQEJARYOcm9vdEBsb2NhbGhvc3QwIBcNMjUwODIzMjEx
NTM0WhgPMjA1MDA4MTcyMTE1MzRaMIGBMQswCQYDVQQGEwJGUjEMMAoGA1UECAwD
QlpIMRAwDgYDVQQHDAdSb3Njb2ZmMQwwCgYDVQQKDAMxZTExDTALBgNVBAsMBEBs
YW4xFjAUBgNVBAMMDWVzcDgyNjYubG9jYWwxHTAbBgkqhkiG9w0BCQEWDnJvb3RA
bG9jYWxob3N0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEm72/P2sPpmdC4SKL
OEynoLwBN8/eoqUfNrZnVMT3cOLAg83hKing25eVLTbkGTQ+/d5lMdT8hBKWvPd0
yNt276MhMB8wHQYDVR0OBBYEFFwacWYrC4VGWNzv/2FRt98EvovoMAoGCCqGSM49
BAMCA0cAMEQCIHgyBIdsGhEW8gX8SUwuvvU5wXN0szYyjEfPqd+PUHJzAiAXJsjJ
j0Xq0Uu5lJCVai7KwLVjaJm3zD48fahVH8wN+g==
-----END CERTIFICATE-----
)EOT";
}

#endif // CERTIFICATE_GENERATED_H_
