#ifndef _certificate_H_
#define _certificate_H_

namespace certificate {
    typedef enum { CT_ECC=0, CT_RSA=1 } CertType;

    const char dname[] = "webrelay";

    const CertType serverCertType = CT_ECC;

    const char serverKey[] PROGMEM = R"EOT(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIOq6BcHwCz4jSG3H2x996iyShhjfmh0Dol1OtR9uZQXMoAoGCCqGSM49
AwEHoUQDQgAE35lUvkqwAUK/wDmlvg4gvy33bv+Be8HpS44jUULCgfkmQBMbEgnO
j7fLHHt4hPPObtyeZILScXWx8oS25FFWLA==
-----END EC PRIVATE KEY-----
)EOT";

    const char serverCert[] PROGMEM = R"EOT(
-----BEGIN CERTIFICATE-----
MIICsjCCAligAwIBAgIUeGHTrY8KAewKvCgpttZlzwlV3J4wCgYIKoZIzj0EAwIw
gZMxCzAJBgNVBAYTAkZSMQwwCgYDVQQIDANCWkgxEDAOBgNVBAcMB1Jvc2NvZmYx
DDAKBgNVBAoMAzFlMTENMAsGA1UECwwEQGxhbjEXMBUGA1UEAwwOd2VicmVsYXku
bG9jYWwxLjAsBgkqhkiG9w0BCQEWHzIuNzE4MjgxODNFMCt3ZWJyZWxheUBnbWFp
bC5jb20wHhcNMjAxMTE0MDkzMTMwWhcNNDUxMTA4MDkzMTMwWjCBkzELMAkGA1UE
BhMCRlIxDDAKBgNVBAgMA0JaSDEQMA4GA1UEBwwHUm9zY29mZjEMMAoGA1UECgwD
MWUxMQ0wCwYDVQQLDARAbGFuMRcwFQYDVQQDDA53ZWJyZWxheS5sb2NhbDEuMCwG
CSqGSIb3DQEJARYfMi43MTgyODE4M0UwK3dlYnJlbGF5QGdtYWlsLmNvbTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABN+ZVL5KsAFCv8A5pb4OIL8t927/gXvB6UuO
I1FCwoH5JkATGxIJzo+3yxx7eITzzm7cnmSC0nF1sfKEtuRRViyjgYcwgYQwHQYD
VR0OBBYEFPXP3JLB+AdzMx24N5yEAHZ4spL6MB8GA1UdIwQYMBaAFPXP3JLB+Adz
Mx24N5yEAHZ4spL6MA8GA1UdEwEB/wQFMAMBAf8wMQYDVR0RBCowKIIOd2VicmVs
YXkubG9jYWyCEHJlbGF5Ym9hcmQubG9jYWyHBMCoBAEwCgYIKoZIzj0EAwIDSAAw
RQIgeWNMnQGmS++RlwSOWJS8VxiR8y53GvrLrcjQCvTi5yQCIQD+T1r/98F2n5zV
I3CVqhsjbik4XsUicsYkfwLErJe9bA==
-----END CERTIFICATE-----
)EOT";
}

#endif // _certificate_H_
